config/routes.rb
Rails.application.routes.draw do
  root to: 'top#index'

  # For OmniAuth
  get '/auth/:provider/callback', to: 'sessions#callback'
  get '/auth/failure',            to: 'sessions#failure'
  get '/logout',                  to: 'sessions#destroy', as: :logout
  post '/top/tweet'               => 'top#tweet', as: :tweet

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user, optional: true

  validates :provider, presence: true
  validates :uid,      presence: true

  def auth_update(auth)
    case auth['provider']
    when 'facebook'
      image_path = "https://graph.facebook.com/#{auth['info']['nickname'].presence || auth["uid"]}/picture?width=200&height=200"
    when 'twitter'
      image_path = auth['info']['image'].to_s.gsub('_normal', '') rescue nil
    when 'github'
      image_path = "#{auth['info']['image']}&size=200" rescue nil
    end

    gender   = auth['extra']['raw_info']['gender'] rescue nil
    location = (auth['info']['location'].presence || auth['extra']['raw_info']['location']) rescue nil

    self.name     = auth['info']['name']     if auth['info']['name'].present?
    self.nickname = auth['info']['nickname'] if auth['info']['nickname'].present?
    self.image    = image_path               if image_path.present?
    self.email    = auth['info']['email']    if auth['info']['email'].present?
    self.gender   = gender                   if gender.present?
    self.location = location                 if location.present?
    self.save!
  end

  class << self
    def create_with_omniauth(auth)
      authentication = Authentication.new
      authentication.provider = auth['provider']
      authentication.uid      = auth['uid']

      if auth['info'].present?
        authentication.name     = auth['info']['name']
        authentication.nickname = auth['info']['nickname']
        authentication.image    = auth['info']['image']
        authentication.email    = auth['info']['email']
        authentication.location = auth['info']['location']
      end

      if auth['credentials'].present?
        authentication.token  = auth['credentials']['token']
        authentication.secret = auth['credentials']['secret']
      end

      if auth['extra'].present? and auth['extra']['raw_info'].present?
        authentication.gender   = auth['extra']['raw_info']['gender']
        authentication.location = auth['extra']['raw_info']['location'] if authentication.location.blank?
      end

      authentication.save!

      return authentication
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :authentications

  def https_image
    self.image.gsub('http://', 'https://')
  end

  class << self
    def create_with_auth(authentication, request)
      user = User.new
      user.name                = (authentication.nickname.presence || authentication.name)
      user.image               = authentication.image    if authentication.image.present?
      user.email               = authentication.email    if authentication.email.present?
      user.last_login_provider = authentication.provider if authentication.provider.present?
      user.last_login_at       = Time.now
      user.user_agent          = request.env['HTTP_USER_AGENT'] rescue 'error'
      user.save!

      authentication.user_id = user.id
      authentication.save!

      return user
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate

  private

  def authenticate
    unless signed_in?
      session[:request_url] = request.url

      redirect_to :root and return
    end
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  def signed_in?
    User.where(id: session[:user_id]).exists?
  end
  helper_method :signed_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate

  def callback
    auth = request.env["omniauth.auth"]
    authentication = Authentication.find_by(provider: auth["provider"], uid: auth["uid"]) || Authentication.create_with_omniauth(auth)
    authentication.auth_update(auth)

    user = User.find_by(id: authentication.user_id) || User.create_with_auth(authentication, request)

    session[:user_id] = user.id

    unless session[:request_url].blank?
      redirect_to session[:request_url]
      session[:request_url] = nil
      return
    end

    redirect_to :root and return
  end

  def destroy
    session[:user_id] = nil

    redirect_to :root and return
  end

  def failure
    flash[:alert] = 'Auth Failure'

    redirect_to :root and return
  end
end

app/controllers/top_controller.rb
require 'twitter'
class TopController < ApplicationController
  skip_before_action :authenticate


  def index
  end

  def tweet
      client = Twitter::REST::Client.new do |config|
        list_tuning = ["Regular", "Half step down", "Whole step down", "Half + Whole step down", "Drop D", "Drop C#", "Drop B"]
        # applicationの設定
        config.consumer_key         = Settings.twitter_key
        config.consumer_secret      = Settings.twitter_secret
        # ユーザー情報の設定
        user_auth = current_user.authentications.first
        config.access_token         = user_auth.token
        config.access_token_secret  = user_auth.secret

        idx = rand(list_tuning.size)
        tuning = list_tuning[idx]
        text = %(今日のチューニング: #{tuning} from ruby app)
        config.update(text)

        redirect_to root_path, notice: "ツイートしました"

        #まだログインしてなかったときはどうするか
        #rescueで対応？
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_user_icon.html.haml
- if user.present?
  = link_to_if user.name.present?, image_tag(user.https_image, size: size, class: klass), "#{Settings[user.last_login_provider + '_page']}#{user.name}", target: '_blank', title: user.name, rel: 'tooltip', 'data-original-title' => user.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= Settings.app_name
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{ class: [controller_name, action_name], id: [controller_name, action_name] }
    = link_to Settings.app_name, :root

    - if signed_in?
      = render partial: '/layouts/user_icon', locals: { user: current_user, size: "18x18", klass: "margin_minus2" }
      = link_to "Top",    root_path
      = link_to "Logout", logout_path
    - else
      = link_to 'Twitterでログイン',  '/auth/twitter'

    = simple_format(flash[:notice], style: "color: green;") if flash[:notice].present?
    = simple_format(flash[:alert], style: "color: red;")    if flash[:alert].present?

    = yield

    %br/
    %br/

app/views/layouts/application_BACKUP.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.haml
%h1= "#{Settings.app_name}"
= form_tag tweet_path do
  = submit_tag '今日のチューニングをツイートする'